language: rust
rust:
  - nightly
sudo: false
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
    - CARGO_INCREMENTAL=0  # not needed for CI builds
script:
  - cargo test
notifications:
  email:
    on_success: never
